/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Thu Jul 12 04:45:52 2018
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


